language: node_js
sudo: false
node_js: lts/*
env:
  matrix:
  - CMD=build
  - CMD=test
  - CMD=lint
before_install:
- openssl aes-256-cbc -K $encrypted_221602e78f05_key -iv $encrypted_221602e78f05_iv -in .travis/deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key
- git config --global user.name "9renpoto"
- git config --global user.email "9renpoto@gmail.com"
script:
- npm run $CMD
after_success:
- '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$CMD" == "build" ] && bash ./deploy.sh'
notifications:
  email: false
